### ISSUE TITLE
Implement kernelversion fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#104]
## Use Case
Implement `kernelversion` fact for Ubuntu

## Describe the Solution You Would Like
Implement `kernelversion` fact similar to the one for [solaris](https://github.com/puppetlabs/facter-ng/blob/master/lib/facts/solaris/kernelversion.rb). The `uname_resolver` should be called with `:kernelrelease` and the output should be parsed. Another option is to parse `/proc/version` file.

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,kernelversion]'
```

## Example command
```
./bin/facter kernelversion
```

## Example output
```
4.15.0
```

## Validate implementation locally
```
./check.sh
```

**Comment by joelmheim** [comment]
I'm looking into this one. Hope to provide a PR if I can work it out.

**Comment by sebastian-miclea** [comment]
Excellent job! 
Thank you again for your contribution!
