### ISSUE TITLE
Implement FQDN fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#105]
## Use Case
Implement `networking.fqdn` fact for Ubuntu

## Describe the Solution You Would Like
Implement `networking.fqdn` by combining the result from [Hostname resolver](https://github.com/puppetlabs/facter-ng/blob/master/lib/resolvers/hostname_resolver.rb) and [NetworkingDomain resolver](https://github.com/puppetlabs/facter-ng/blob/master/lib/resolvers/networking_domain_resolver.rb) 

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,networking.fqdn]'
```

## Example command
```
./bin/facter networking.fqdn
```

## Example output
```
hostname.puppetlabs.net
```

## Validate implementation locally
```
./check.sh
```

**Comment by joelmheim** [comment]
Working on a PR. Should be ready shortly.

**Comment by IrimieBogdan** [comment]
Great work on this PR!
