### ISSUE TITLE
Implement memory.swap.available fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#115]
## Use Case
Implement `memory.swap.available` fact for Ubuntu

## Describe the Solution You Would Like
Implement `memory.swap.available` fact similar to the one for [fedora](https://github.com/puppetlabs/facter-ng/blob/master/lib/facts/fedora/memory/swap/available.rb).

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,memory.swap.available]'
```

## Example command
```
./bin/facter memory.swap.available
```

## Example output
```
808.25 MiB
```

## Validate implementation locally
```
./check.sh
```

**Comment by martingoldstone** [comment]
I'd like to take a go at this
