### ISSUE TITLE
Implement memory.swap.available_bytes fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#116]
## Use Case
Implement `memory.swap.available_bytes` fact for Ubuntu

## Describe the Solution You Would Like
Implement `memory.swap.available_bytes` fact similar to the one for [fedora](https://github.com/puppetlabs/facter-ng/blob/master/lib/facts/fedora/memory/swap/available_bytes.rb).

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,memory.swap.available_bytes]'
```

## Example command
```
./bin/facter memory.swap.available_bytes
```

## Example output
```
847511552
```

## Validate implementation locally
```
./check.sh
```

**Comment by henriquepjv** [comment]
@IrimieBogdan also done this related issue :smile:

**Comment by IrimieBogdan** [comment]
@henriquepjv great job on the prompt PR #121 . There are multiple memory facts, very similar to one another, if you want have a look over them.
