### ISSUE TITLE
Implement memory.swap.capacity fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#117]
## Use Case
Implement `memory.swap.capacity` fact for Ubuntu

## Describe the Solution You Would Like
Implement `memory.swap.capacity` fact similar to the one for [fedora](https://github.com/puppetlabs/facter-ng/blob/master/lib/facts/fedora/memory/swap/capacity.rb).

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,memory.swap.capacity]'
```

## Example command
```
./bin/facter memory.swap.capacity
```

## Example output
```
73.69%
```

## Validate implementation locally
```
./check.sh
```

**Comment by henriquepjv** [comment]
Hi!! May I help you with this task?

**Comment by IrimieBogdan** [comment]
Sure @henriquepjv, if you have any questions please let me know.

**Comment by IrimieBogdan** [comment]
I have labeled this Issue as in progress.

**Comment by IrimieBogdan** [comment]
@henriquepjv great job on PR #120
