### ISSUE TITLE
Using ruby invalid conventions

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/facter-ng#268]
## Describe the Bug
Ruby throws

```
Failure/Error: require 'facter-ng'
SyntaxError:
  /home/travis/build/puppetlabs/pdk/vendor/bundle/ruby/2.1.0/gems/facter-ng-4.0.4/lib/resolvers/mountpoints_resolver.rb:21: syntax error, unexpected '.'
              match&.captures&.first
```

On Ruby 2.1.9

The gemspec does not specify a minimum ruby version.

https://github.com/puppetlabs/facter-ng/blob/1a5bcdda8f3aab6ae615279bde2fbca1c2d360a7/lib/resolvers/mountpoints_resolver.rb#L21

## Expected Behavior
Facter-ng should support AND TEST on the specified ruby versions int he gemspec (>= 0)

## Steps to Reproduce
https://travis-ci.org/puppetlabs/pdk/jobs/643819750?utm_medium=notification&utm_source=github_status

## Environment
 - Version 4.0.4
 - Platform - N/A

## Additional Context
Would also need to scour the code for other "modern" rubyisms that won't work on older Ruby's e.g. 2.1.9

**Comment by mihaibuzgau** [comment]
Fixed in: https://github.com/puppetlabs/facter-ng/pull/277
We're currently not planning on supporting Ruby < 2.3
