### ISSUE TITLE
Implement kernelmajversion fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#75]
## Use Case
Implement `kernelmajversion` fact for Ubuntu

## Describe the Solution You Would Like
Implement `kernelmajversion` fact similar to the one for [solaris](https://github.com/puppetlabs/facter-ng/blob/master/lib/facts/solaris/kernelmajversion.rb)

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,kernelmajversion]'
```

## Example command
```
./bin/facter kernelmajversion
```

## Example output
```
19.0
```

## Validate implementation locally
```
./check.sh
```

**Comment by IrimieBogdan** [comment]
@AlexAvlonitis, as we are quite a small number of contributors to this respo, your contribution with Ubuntu facts makes a [difference](https://docs.google.com/spreadsheets/d/1nLFU9_TEcSismnFqCySLBHdWfE-hcojuO54LWblGlGU/edit?usp=sharing).  If you want I can provide some facts that are more challenging (they require writing a resolver) .

**Comment by AlexAvlonitis** [comment]
happy to help @IrimieBogdan when i have spare time :)
