### ISSUE TITLE
Implement timezone fact for Ubuntu

### ISSUE THREAD

**Issue by IrimieBogdan** [puppetlabs/facter-ng#95]
## Use Case
Implement `timezone` fact for Ubuntu

## Describe the Solution You Would Like
Implement `timezone` using the [timezone_resolver](https://github.com/puppetlabs/facter-ng/blob/master/lib/resolvers/timezone_resolver.rb).

## Additional Context
The facts can be generated using a rake task. E.g. 
```
rake 'create_fact[ubuntu,timezone]'
```

## Example command
```
./bin/facter timezone
```

## Example output
```
EEST
```

## Validate implementation locally
```
./check.sh
```

**Comment by IrimieBogdan** [comment]
@m8051 you did great work  with the first issues, if you want something that is a little more challenging have a look  #78

**Comment by m8051** [comment]
> @m8051 you did great work with the first issues, if you want something that is a little more challenging have a look #78

Thanks @IrimieBogdan , adding the #78 to my list, will try to work on it asap ...
